---
title: "Snowy Plover Management"
author: "Jamie Miller"
date: "May 31, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
source("../R/predator_mgmt.R")
source("../R/snpl.R")
source("../R/habit.R")
```

## 1. Set up Leslie Matrices for snowy plover age structure population model
```{r setup matrix manually}
# Four Age Classes: Egg, Chick, Juvenile, Adult
nclasses = 4

# create a growth matrix to store fecundity and survivorship information
gmatrix=matrix(nrow=nclasses, ncol=nclasses)
gmatrix

# change NAs to zero
gmatrix[]=0.0
gmatrix

# assign values for fecundity for each of the age classes 
# notes that fecundity rates are births per capita (number in class) per time step
# At VAFB: average fledge succecss is 1.3 fledges per male; in 2019, 220 adults, 1156 eggs, 588 chicks, 134 fledges 
### 1156/220 # 5.25 eggs per adult
### 220/1156 # 0.19 adults per egg; that makes no sense as a measure of fecundity

fecund =  c(0,0,0,5.25)

# enter into our matrix
gmatrix[1,]=fecund
 
# Survivorship probabilities (to the next class) per time step, using 2019 data.
#588/1156 # 0.509 Hatch Rate, Chicks/Eggs
#134/588 # 0.228 Fledge rate, Fledges/Chicks
 
gmatrix[2,1]=0.509  
gmatrix[3,2]=0.228
gmatrix[4,3]=0.33 #Adjust this number

# Adult survivorship to the following year
gmatrix[4,4]=0.6 #Adjust this number
gmatrix

```

Now use the matrix to grow a population 
```{r test matrix}
# start with an initial population, lets say 1 individual in each class

#p0 = rep(1, times=nclasses)
p0 = c(1156,588,134,220)

# advance to the next time step
# note the use of matrix multiplication
p1 = gmatrix %*% p0
p1

# has the total number of individuals changed?
sum(p1)
sum(p0)

# growth rate
sum(p1)/sum(p0)

#add another year
p2 = gmatrix %*% p1
p3 = gmatrix %*% p2

# combined
pop = cbind.data.frame(p0,p1,p2,p3)
pop$age = c("1_Eggs","2_Chicks","3_Juveniles","4_Adults")

popl = pop %>% gather(key="timestep",value="pop",-age)
ggplot(popl, aes(timestep, pop,fill=as.factor(age)))+geom_col(position="dodge")+labs(fill="Age Group")

# I'm not sure this accomplishes what I want it to accomplish.
# Use the snpl.R function instead.

```


## 2. Use the snpl.R function to calcutlate the age structure model and predict adult population over time. 
```{r multitime}

source("../R/snpl.R")

# At VAFB: average fledge succecss is 1.3 fledges per male; in 2019, 220 adults, 1156 eggs, 588 chicks, 134 fledges 
### 1156/220 # 5.25 eggs per adult
### 220/1156 # 0.19 adults per egg; that makes no sense as a measure of fecundity

# Fecundity Rates
F_adult = 5.25*0.6 # 1156/220 # 5.25 eggs per adult, M to F ratio of 0.6 (3 males to 2 females). represents number eggs per female; adjust for diff sex ratios

# Survivorship probabilities (to the next class) per time step, using 2019 data.
#588/1156 # 0.509 Hatch Rate, Chicks/Eggs
#134/588 # 0.228 Fledge rate, Fledges/Eggs

# Survivorship - based on 2019 survivoral probabilities
p_egg = 1-50.9/100 # Hatch rate
p_chick = 1-22.8/100 # Fledge rate 
p_fledge = 1-33/100 # First Winter Survival, assume 33% make it; Adjust this value as needed.
p_adult = 1-66/100 # Adult survivorship, assume 66% make it; Adjust this value as needed.

####===============================================================================Please take a look.
### It seems that "p_xxx" value from above is actually a "deathrate" not a "possibility of  surviving".
### And I guess Leslie matrix(4x4) should take in (possibility of surviving) not (deathrate)
###=================================================================================================



# initial population parameters
# In 2019, 1156 eggs, 588 chicks, 134 fledges, 220 adults
ini = c(1156,588,134,220)
n_years = 15
fert_snpl = c(0,0,0,F_adult)
surv_snpl = c(p_egg,p_chick,p_fledge,p_adult)
K = 10000 # VAFB Carrying capacity, based on Recover Goals; lookup actual value and adjust 
   ### K is not working in the model the way I thin kit should. Want it to apply only to adults, but it is applying to all life stages.
   ### Consider removing K from model and representing this information graphically.
### ===================================================================================
### changed code in snpl.R(line 41~44), and now K only applies to adult population. ###
### ===================================================================================

snpl_pop=snpl_popK(fert_snpl, surv_snpl, ini, n_years,K) # Population Structure

head(snpl_pop)

# Plot adult population by year
year = seq(from=1, to=n_years)
snpl_tot = cbind.data.frame(year=year, adult_pop=snpl_pop$pop_structure[4,])

ggplot(snpl_tot, aes(year, adult_pop)) +
         geom_col() +
         labs(y="Total Adult SNPL Population")


# Plot all ages by year
snpl_ages = cbind.data.frame(year=year, t(snpl_pop$pop_structure))
snpl_agesl = snpl_ages %>% 
  gather(key="agecat", value="pop",-year)

ggplot(snpl_agesl, aes(year, pop, fill=agecat)) +
  geom_col() +
  labs(y="Population", fill="Age Group")

# The following graphs predict snowy plover adult population and age structure over 15 years if 2019 fecundity and survivorship rates apply to all years.

```
<br><br>

## 3. Apply Habitat and Predator Management Functions
```{r}
# Output matrix of predator MGMT should go into snpl.R

source("../R/predator_mgmt.R")
source("../R/snpl.R") # I don't know why but RMD keep losting snpl_pop3 function from its environment.

F_adult = 5.25*0.6 # 1156/220 # 5.25 eggs per adult, M to F ratio of 0.6 (3 males to 2 females). represents number eggs per female; adjust for diff sex ratios
ini = c(1156,588,134,220)
n_years = 15
fert_snpl = c(0,0,0,F_adult)
surv_snpl = c(p_egg,p_chick,p_fledge,p_adult)
K = 10000
year = seq(from=1, to=n_years)


funding = 10 #in thousands?
raven_p = raven_pop(n_years, 80, 0.4, 200, mgmt_action = T, funding, rmv_eff= 4, min = 0.2, limit= 0.5)
falcon_p = falcon_pop(n_years, 40, 0.3, 100, mgmt_action = T, funding, rmv_eff= 4, min = 0.3, limit = 0.8)

tmp = list(egg_predation(raven_p), chick_predation(raven_p, falcon_p), juvenile_predation(falcon_p), adult_predation(falcon_p))
tmp2 = list(raven_p, falcon_p)
predation_matrix = tmp %>% unlist() %>% matrix(ncol=n_years, byrow = T) # row1= egg, row2= chick, row3=juvenile, row4=adult
predatorpop_matrix = tmp2 %>% unlist() %>% matrix(ncol=n_years, byrow = T) # row1= raven, row2=falcon
rm(tmp,tmp2)

area = habitat_area(1, init_mgmt = T, maint_mgmt = T, init_funding = 200, maint_funding = 30, n_time = n_years)



### This DOES WORK:
    ### Survivorship = 1-deathr
    ### deathr = 1 - survivorship

    ### deathr = predation + b = a * predator_pop + b
    ### deathr_0 = a * predator_0 + b
    
    ### let's assume 80% is gone by predation. and the other 20% is other cause.
    ### a = 0.8 * deathr_0/predator_pop0
    ### b = 0.2 * deathr_0 <- some kind of constant/intercept, but affected by snpl population change.
    ### b_t = 0.2 * deathr_0 * snpl_t/snpl_0

    ### deathr_t = a * predator_t + b_t
    ###          = 0.8 * deathr_0/predator_0 * predator_t + 0.2 * deathr_0 * snpl_t/snpl_0

    ### Survivorship_t = 1 - deathr_t
    ###                = 1- (0.8 * deathr_0/predator_0 * predator_t) - 0.2 * deathr_0 * total_t/total_0

### With survivorship, not deathrate.
p_egg = 50.9/100 # Hatch rate
p_chick = 22.8/100 # Fledge rate 
p_fledge = 33/100 # First Winter Survival, assume 33% make it; Adjust this value as needed.
p_adult = 66/100 # Adult survivorship, assume 66% make it; Adjust this value as needed.
surv_snpl = c(p_egg,p_chick,p_fledge,p_adult)

snpl_popk3=snpl_pop3(fert_snpl, surv_snpl, ini, n_years, K, predatorpop_matrix, area) # Test purpose
snpl_tot3 = cbind.data.frame(year=year, adult_pop=snpl_popk3$pop_structure[4,])



# Plot all ages by year
{
  p0 <- ggplot()+
    geom_line(aes(seq(1, ncol(predatorpop_matrix)),predatorpop_matrix[2,], color="falcon"))+
    geom_line(aes(seq(1, ncol(predatorpop_matrix)),predatorpop_matrix[1,], color="raven"))+
    labs(y="Population", x="year", color ="Species")

  p1<-ggplot(snpl_tot3, aes(year, adult_pop)) +
         geom_col() +
         labs(y="Total Adult SNPL Population")
  
  snpl_ages3 = cbind.data.frame(year=year, t(snpl_popk3$pop_structure))
  snpl_agesl3 = snpl_ages3 %>% 
  gather(key="agecat", value="pop",-year)

  p2<-ggplot(snpl_agesl3, aes(year, pop, fill=agecat)) +
  geom_col() +
  labs(y="Population", fill="Age Group")
  
  show(p0)
  show(p1)
  show(p2)
}
```
<br><br>

### 4. Apply Sobol sensitivity analysis
```{r}
source("../R/predator_mgmt.R")
source("../R/snpl.R")
source("../R/habit.R")

F_adult = 5.25*0.6 # 1156/220 # 5.25 eggs per adult, M to F ratio of 0.6 (3 males to 2 females). represents number eggs per female; adjust for diff sex ratios
ini = c(1156,588,134,220)
n_years = 15

p_egg = 50.9/100 # Hatch rate
p_chick = 22.8/100 # Fledge rate 
p_fledge = 33/100 # First Winter Survival, assume 33% make it; Adjust this value as needed.
p_adult = 66/100 # Adult survivorship, assume 66% make it; Adjust this value as needed.

fert_snpl = c(0,0,0,F_adult)
surv_snpl = c(p_egg,p_chick,p_fledge,p_adult)


np = 1000

habitat_init_funding = rnorm(mean = 200, sd = 50, n=np)
habitata_maint_funding = rnorm(mean = 50, sd = 20, n=np)
pred_funding = rnorm(mean = 10, sd = 4, n=np)
raven_min = runif(n=np, min = 0, max = 0.5)
raven_lim = runif(n=np, min = 0.5, max = 1)
falcon_min = runif(n=np, min =0, max = 0.5)
falcon_lim = runif(n=np, min =0, max = 1)
X1 = cbind.data.frame(habitat_init_funding=habitat_init_funding, habitata_maint_funding=habitata_maint_funding,
                      pred_funding=pred_funding, raven_min=raven_min, raven_lim=raven_lim,
                      falcon_min=falcon_min, falcon_lim=falcon_lim)

habitat_init_funding = rnorm(mean = 200, sd = 10, n=np)
habitata_maint_funding = rnorm(mean = 30, sd = 5, n=np)
pred_funding = rnorm(mean = 10, sd = 4, n=np)
raven_min = runif(n=np, min = 0, max = 0.5)
raven_lim = runif(n=np, min = 0.5, max = 1)
falcon_min = runif(n=np, min =0, max = 0.5)
falcon_lim = runif(n=np, min =0, max = 1)
X2 = cbind.data.frame(habitat_init_funding=habitat_init_funding, habitata_maint_funding=habitata_maint_funding,
                      pred_funding=pred_funding, raven_min=raven_min, raven_lim=raven_lim,
                      falcon_min=falcon_min, falcon_lim=falcon_lim)

library(sensitivity)

sens_P = sobol2007(model = NULL,X1, X2, nboot = 500)


wrapper = function(n, initialP, fertility, survivorship,
                   habitat_init_funding, habitata_maint_funding, pred_funding,
                   raven_min, raven_lim,falcon_min, falcon_lim,
                   func) {
  
  area = habitat_area(1, init_funding = habitat_init_funding, maint_funding = habitata_maint_funding, n_time=n)
  
  raven_p = raven_pop(n, P0=80, K=160, pred_mgmt_funding=pred_funding,
                      min=raven_min ,limit=raven_lim)
  
  falcon_p = falcon_pop(n, P0=50, K=100, pred_mgmt_funding=pred_funding,
                      min=falcon_min ,limit=falcon_lim)
  
  predatorpop_matrix = list(raven_p, falcon_p)
  predatorpop_matrix = predatorpop_matrix %>% unlist() %>% matrix(ncol=n, byrow = T) # row1= raven, row2=falcon

  snpl_p = snpl_pop3(fertility, survivorship, initialP, nstep=n, K=5000, predatorpop_matrix, area)

  return(snpl_p$total_pop)
}


allresults = mapply(FUN=wrapper, 
                   habitat_init_funding=sens_P$X$habitat_init_funding,
                   habitata_maint_funding=sens_P$X$habitata_maint_funding,
                   pred_funding=sens_P$X$pred_funding,
                   raven_min=sens_P$X$raven_min, raven_lim=sens_P$X$raven_lim,
                   falcon_min=sens_P$X$falcon_min, falcon_lim=sens_P$X$falcon_lim,
                   MoreArgs=list(n=n_years, initialP=ini, fertility=fert_snpl, survivorship=surv_snpl,
                                 func=snpl_pop3)
                   )

ggplot(data.frame(total_pop=allresults), aes(x=total_pop))+geom_density()

sens_P_totalpop = sensitivity::tell(sens_P, allresults)
sens_P_totalpop$S
sens_P_totalpop$T
plot(sens_P_totalpop)

tmp = cbind.data.frame(sens_P_totalpop$X, total_pop=sens_P_totalpop$y)
ggplot(tmp, aes(pred_funding, total_pop))+geom_point()+labs(x="Parm",y="total pop")

```